markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
baseurl: http://fleurer.github.io
auto: false
destination: ./_site
title: "F叔的学习笔记"

author_name: fleuria
author_email: me.ssword@gmail.com
